import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import PrivyProviderWrapper from "@/lib/providers/PrivyProvider";
import QueryProvider from "@/lib/providers/QueryProvider";
import { Toaster } from "@/components/ui/toaster";
import { GoogleTagManager } from "@next/third-parties/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="/assets/favicon.svg"
          type="image/x-icon"
        />
        <meta
          name="google-site-verification"
          content="yBpTSxcXRR6837rTsEHRbs9gEzxjr3ZiaHFmIM4Mkqc"
        />
      </head>
      <GoogleTagManager gtmId="G-M081SD7ZD3" />
      <body className="bg-background antialiased">
        <PrivyProviderWrapper>
          <QueryProvider>
            <Navbar />
            {children}
            <Footer />
          </QueryProvider>
        </PrivyProviderWrapper>
        <Toaster />
      </body>
    </html>
  );
}
